use_frameworks!
source "https://github.com/mintforpeople/mint-podspec-repo.git"

target 'robobo-speech-ios_Example' do
  pod 'robobo-framework-ios-pod','~>0.1.0'
  pod 'robobo-speech-ios', :path => '../'

  target 'robobo-speech-ios_Tests' do
    inherit! :search_paths

    
  end
end
